experiment:
  name: exp_to_test

predict:
  name: atlas
  model: epoch_500.pt # null for best or model epoch_10.pt
  images_list: "val.csv" #"val_atlas_vertebra_fold_0.csv"
  num_samples: 100
  prefix: val
  batch_size: 2
  annotation_label: annotation_label.txt
  metrics: ["PCK_heatmaps", "AED_heatmaps"]
  kp_metrics: ["PCK", "AED"]
  params:
    root_dir: "./data/atlas_full"
    annotation_file: pose_dataset.csv
    input_size:
      - 256
      - 256