model:
  name: stacked_hourglass_pytorch
  backend: pytorch
  special_mode: cut_five_dim
  params:
    input_channels: 3
    num_keypoints: 23
    nstack: 2
    inp_dim: 255
    oup_dim: 23

keypoint_format: heatmaps

loss:
  name: multi_AED # multi_MSE, multi_L2Norm, multi_AED, multi_Huber, Weighted
  use_heatmaps: False
  params:
    losses: ["multi_MSE", "multi_AED"]
    weights: [0.4, 0.6]

metrics:
  names: [PCK_heatmaps, AED_heatmaps]

dataset:
  params:
    input_size:
      - 256
      - 256
    output_size:
      - 64
      - 64

train:
  scheduler: CosineAnnealingWarmRestarts #CosineAnnealingLR, CosineAnnealingWarmRestarts
  CosineAnnealingLR:
    T_max: 50 
    eta_min: 1e-6
  CosineAnnealingWarmRestarts:
    T_0: 4
    T_mult: 2
    eta_min: 1e-8
