model:
  name: stacked_hourglass_pytorch
  backend: pytorch
  special_mode: cut_five_dim
  params:
    input_channels: 3
    num_keypoints: 17
    nstack: 2
    inp_dim: 255
    oup_dim: 17

keypoint_format: heatmaps

loss:
  name: multi_MSE

metrics:
  names: ["PCK_heatmaps"]

dataset:
  params:
    input_size:
      - 256
      - 256
    output_size:
      - 64
      - 64