# Basic configuration, can be overwritten by other files

experiment:
  name: EXP_23_3_0
  continue_from: null  # null or checkpoint (epoch_10.pt/best.pt)

train:
  batch_size: 8
  lr: 0.01
  epochs: 10
  save_every_epoch: 10
  device: null #"cuda:4"
  use_tensorboard: False