# Basic configuration, can be overwritten by other files

model:
  name: test_model_heatmap_pytorch #test_model_heatmap_pytorch #stacked_hourglass_pytorch #test_model_heatmap_keras
  framework: pytorch
  special_mode: cut_five_dim
  params:
    input_channels: 3
    num_keypoints: 17
    
keypoint_format: heatmaps

dataset:
  name: random_heatmaps
  split: ["train2017", "val2017"]
  params:
    num_keypoints: 17

loss:
  name: MSE

metrics:
  names: ["PCK"]

train:
  batch_size: 2
  lr: 0.01
  epochs: 2