# List of all configurations, overwritten sequentially; the basic configuration must always be first
configs:
  - configs/base.yaml #Always must be first!
  # setting 1
  # - configs/models/stacked_hourglass_pytorch.yaml
  # setting 2
  - configs/models/test_pytorch.yaml
  - configs/datasets/coco_dataset.yaml