# List of all configurations, overwritten sequentially; the basic configuration must always be first
configs:
  - configs/base.yaml #Always must be first!
  - configs/models/stacked_hourglass_pytorch.yaml